CREATE TABLE t_menus (
     id bigint AUTO_INCREMENT,
     parent_id bigint NOT NULL DEFAULT '0' COMMENT '父级菜单id',
     menu_type tinyint NOT NULL DEFAULT '1' COMMENT '菜单类型 1:目录 2:菜单',
     name varchar(32) NOT NULL DEFAULT '' COMMENT '菜单名称',
     icon varchar(32) NOT NULL DEFAULT '' COMMENT '菜单图标',
     component varchar(128) NOT NULL DEFAULT '' COMMENT '菜单组件',
     component_name varchar(32) NOT NULL DEFAULT '' COMMENT '菜单组件名称',
     path varchar(128) NOT NULL DEFAULT '' COMMENT '菜单路径',
     sort int NOT NULL DEFAULT '0' COMMENT '排序',
     state tinyint NOT NULL DEFAULT '1' COMMENT '状态 1:正常 -1:禁用',
     hidden tinyint NOT NULL DEFAULT '0' COMMENT '是否隐藏 0:显示 1:隐藏',
     always_show tinyint NOT NULL DEFAULT '0' COMMENT '是否一直显示 0:不显示 1:显示',
     no_cache tinyint NOT NULL DEFAULT '0' COMMENT '是否缓存 0:缓存 1:不缓存',
     breadcrumb tinyint NOT NULL DEFAULT '0' COMMENT '是否显示面包屑 0:显示 1:不显示',
     affix tinyint NOT NULL DEFAULT '0' COMMENT '是否固定在tagsView 0:不固定 1:固定',
     no_tags_view tinyint NOT NULL DEFAULT '0' COMMENT '是否在tagsView显示 0:显示 1:不显示',
     operator_id bigint NOT NULL DEFAULT '0' COMMENT '操作人id',
     operator varchar(32) NOT NULL DEFAULT '' COMMENT '操作人名称',
     created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     INDEX idx_name (name),
     INDEX idx_parent_id (parent_id),
     PRIMARY KEY (id)
) ENGINE = InnoDB COLLATE utf8mb4_general_ci COMMENT '菜单表';