// Code generated by goctl. DO NOT EDIT!
// Source: permissionBase.proto

package server

import (
	"context"

	"github.com/liangqianyang/permissionBase/internal/logic/permissionbase"
	"github.com/liangqianyang/permissionBase/internal/svc"
	"github.com/liangqianyang/permissionBase/pb/permissionBase"
)

type PermissionBaseServer struct {
	svcCtx *svc.ServiceContext
	permissionBase.UnimplementedPermissionBaseServer
}

func NewPermissionBaseServer(svcCtx *svc.ServiceContext) *PermissionBaseServer {
	return &PermissionBaseServer{
		svcCtx: svcCtx,
	}
}

// CreateMenu 创建菜单
func (s *PermissionBaseServer) CreateMenu(ctx context.Context, in *permissionBase.CreateMenuRequest) (*permissionBase.CreateMenuResponse, error) {
	l := permissionbaselogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

// CreatePermission 创建权限
func (s *PermissionBaseServer) CreatePermission(ctx context.Context, in *permissionBase.CreatePermissionRequest) (*permissionBase.CreatePermissionResponse, error) {
	l := permissionbaselogic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

// UpdateMenu 更新菜单
func (s *PermissionBaseServer) UpdateMenu(ctx context.Context, in *permissionBase.UpdateMenuRequest) (*permissionBase.UpdateMenuResponse, error) {
	l := permissionbaselogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

// CreateRole 创建角色
func (s *PermissionBaseServer) CreateRole(ctx context.Context, in *permissionBase.CreateRoleRequest) (*permissionBase.CreateRoleResponse, error) {
	l := permissionbaselogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}
